# Generated by Django 3.0.2 on 2020-05-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classesBindProfession',
            fields=[
                ('classesCode', models.AutoField(primary_key=True, serialize=False, verbose_name='班级编号')),
                ('professionCode', models.CharField(max_length=21, verbose_name='专业编号')),
                ('addTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '班级绑定专业相关数据',
                'verbose_name_plural': '班级绑定专业相关数据',
            },
        ),
        migrations.CreateModel(
            name='classesManage',
            fields=[
                ('classesCode', models.AutoField(primary_key=True, serialize=False, verbose_name='班级编号')),
                ('classesLevel', models.CharField(max_length=21, verbose_name='班级届数')),
                ('classesName', models.CharField(max_length=21, verbose_name='班级名称')),
                ('addTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '班级管理相关数据',
                'verbose_name_plural': '班级管理相关数据',
            },
        ),
        migrations.CreateModel(
            name='employmentStatus',
            fields=[
                ('statusID', models.IntegerField(primary_key=True, serialize=False, verbose_name='就业状态标识')),
                ('studentCode', models.CharField(max_length=20, verbose_name='学生学号')),
                ('enterpriseName', models.CharField(max_length=25, verbose_name='企业名称')),
                ('enterpriseAddress', models.CharField(max_length=30, verbose_name='企业地址')),
                ('studentPost', models.CharField(max_length=30, verbose_name='学生岗位')),
                ('studentSalary', models.CharField(max_length=30, verbose_name='学生工资')),
                ('noEmployment', models.CharField(max_length=25, verbose_name='未就业原因')),
                ('addTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学生就业状态',
                'verbose_name_plural': '学生就业状态',
            },
        ),
        migrations.CreateModel(
            name='professionManage',
            fields=[
                ('professionCode', models.AutoField(primary_key=True, serialize=False, verbose_name='专业编码')),
                ('professionName', models.CharField(max_length=21, verbose_name='专业名称')),
                ('addTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '专业管理相关数据',
                'verbose_name_plural': '专业管理相关数据',
            },
        ),
        migrations.CreateModel(
            name='studentBindClassesAndProfession',
            fields=[
                ('studentCode', models.AutoField(primary_key=True, serialize=False, verbose_name='学生学号')),
                ('professionCode', models.CharField(max_length=20, verbose_name='专业编码')),
                ('classesCode', models.CharField(max_length=20, verbose_name='班级编号')),
            ],
            options={
                'verbose_name': '学生绑定容器相关数据',
                'verbose_name_plural': '学生绑定容器相关数据',
            },
        ),
        migrations.CreateModel(
            name='studentManage',
            fields=[
                ('studentCode', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='学生学号')),
                ('studentName', models.CharField(max_length=21, verbose_name='学生名称')),
                ('studentSex', models.CharField(max_length=10, verbose_name='学生性别')),
                ('studentPhone', models.CharField(max_length=11, verbose_name='学生电话')),
                ('employmentStatus', models.CharField(max_length=21, verbose_name='就业状态')),
                ('companyName', models.CharField(max_length=30, verbose_name='单位名称')),
                ('companyAddress', models.CharField(max_length=30, verbose_name='单位地址')),
                ('postName', models.CharField(max_length=30, verbose_name='岗位名称')),
                ('studentSalary', models.CharField(max_length=20, verbose_name='实习薪资')),
                ('companyPhone', models.CharField(max_length=11, verbose_name='实习单位电话')),
                ('teacherName', models.CharField(max_length=30, verbose_name='指导老师姓名')),
                ('teacherPhone', models.CharField(max_length=11, verbose_name='指导老师电话')),
                ('studentStatus', models.CharField(max_length=10, verbose_name='学生状态')),
                ('addTime', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学生相关数据',
                'verbose_name_plural': '学生相关数据',
            },
        ),
        migrations.CreateModel(
            name='teacherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=21, verbose_name='账户名称')),
                ('user_pass', models.CharField(max_length=21, verbose_name='账户密码')),
                ('is_login', models.BooleanField(default=False, verbose_name='是否登录')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='初始化时间')),
            ],
            options={
                'verbose_name': '教师基本信息',
                'verbose_name_plural': '教师基本信息',
            },
        ),
    ]
