# Generated by Django 3.0.2 on 2020-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentstatus',
            name='enterpriseAddress',
        ),
        migrations.RemoveField(
            model_name='employmentstatus',
            name='enterpriseName',
        ),
        migrations.RemoveField(
            model_name='employmentstatus',
            name='studentPost',
        ),
        migrations.RemoveField(
            model_name='employmentstatus',
            name='studentSalary',
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='noEmployment',
            field=models.CharField(max_length=3000, verbose_name='未就业原因'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='studentCode',
            field=models.CharField(max_length=30, verbose_name='学生学号'),
        ),
    ]
