# Generated by Django 3.0.2 on 2020-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200524_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentstatus',
            name='noEmployment',
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data1',
            field=models.CharField(default=1, max_length=300, verbose_name='1月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data10',
            field=models.CharField(default=1, max_length=300, verbose_name='10月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data11',
            field=models.CharField(default=1, max_length=300, verbose_name='11月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data12',
            field=models.CharField(default=1, max_length=300, verbose_name='12月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data2',
            field=models.CharField(default=1, max_length=300, verbose_name='2月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data3',
            field=models.CharField(default=1, max_length=300, verbose_name='3月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data4',
            field=models.CharField(default=1, max_length=300, verbose_name='4月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data5',
            field=models.CharField(default=11, max_length=300, verbose_name='5月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data6',
            field=models.CharField(default=1, max_length=300, verbose_name='6月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data7',
            field=models.CharField(default=1, max_length=300, verbose_name='7月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data8',
            field=models.CharField(default=1, max_length=300, verbose_name='8月回访记录'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='data9',
            field=models.CharField(default=1, max_length=300, verbose_name='9月回访记录'),
            preserve_default=False,
        ),
    ]
