# Generated by Django 3.0.2 on 2020-05-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200524_0728'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employmentStatus',
            new_name='employmentReturnVisit',
        ),
    ]
